### ISSUE TITLE
Forward a news message not working as expected

### ISSUE THREAD

**Issue by chrisparana** [bobbimanners/ip65#70]
When pressing F to forward a news message, after entering the address to forward to, "Can't open /PATH/TO/OUTBOX/EMAIL.XXX" is displayed. Unable to forward message.

**Comment by bobbimanners** [comment]
Fixed in 2.1.12.  This was a problem where memory was exhausted so we were unable to open enough disk files.  I managed to eliminate the buffer `halfscreen[]` which was a 1KB block of memory used for scrollback.
